import express from 'express'
import cors from 'cors'
import helmet from 'helmet'
import rateLimit from 'express-rate-limit'
import bcrypt from 'bcrypt'
import jwt from 'jsonwebtoken'
import multer from 'multer'
import QRCode from 'qrcode'
import { z } from 'zod'
import { db, id, categories, locations, seed } from './data.js'
import { analyzeItemDescription, parseSearchQuery } from './services/aiService.js'
import { scoreMatch } from './services/matchingService.js'
import User from './models/User.js'
import Report from './models/Report.js'
import Notification from './models/Notification.js'
import { uploadItemImages, uploadDataUrls } from './services/uploadService.js'

const secret = process.env.JWT_SECRET || 'development-only-change-this-secret'
const publicReport = (report, viewerId = '') => { const value = report.toObject ? report.toObject() : report; const { privateDetails, userId, _id, passwordHash, ...safe } = value; if (viewerId && String(userId) === String(viewerId)) safe.ownerId = String(userId); return { ...safe, id: String(_id || value.id), username: value.username || safe.username || '', contactEmail: value.contactEmail || safe.contactEmail || '', contactWhatsapp: value.contactWhatsapp || safe.contactWhatsapp || '' } }
const ok = (res, data, status = 200) => res.status(status).json({ success: true, data })
const fail = (res, status, message) => res.status(status).json({ success: false, error: { message } })
const tokenFor = (user) => jwt.sign({ id: user.id, role: user.role }, secret, { expiresIn: '7d' })
const userSafe = (user) => { const value = user.toObject ? user.toObject() : user; const { passwordHash, ...safe } = value; return { ...safe, id: String(value._id || value.id) } }
function auth(required = true) { return (req, res, next) => { const value = req.headers.authorization?.replace('Bearer ', ''); if (!value) return required ? fail(res,401,'Please log in to continue.') : next(); try { req.user = jwt.verify(value, secret); next() } catch { return fail(res,401,'Your session has expired. Please log in again.') } } }
const admin = (req,res,next) => req.user?.role === 'admin' ? next() : fail(res,403,'Admin access is required.')
const ownReport = (req,res,next) => { const report = db.reports.find((r) => r.id === req.params.id); if (!report) return fail(res,404,'Report not found.'); if (report.userId !== req.user.id && req.user.role !== 'admin') return fail(res,403,'You can only manage your own reports.'); req.report = report; next() }
function notify(userId, type, title, message, link = '') { db.notifications.unshift({ id:id(), userId, type, title, message, link, read:false, createdAt:new Date().toISOString() }) }
function createMatches(report) {
  const candidates = db.reports.filter((r) => r.id !== report.id && r.type !== report.type && r.status === 'active')
  for (const candidate of candidates) { const lost = report.type === 'lost' ? report : candidate; const found = report.type === 'found' ? report : candidate; const result = scoreMatch(lost, found); if (result.score < 30 || db.matches.some((m) => m.lostReportId === lost.id && m.foundReportId === found.id)) continue; const match = { id:id(), lostReportId:lost.id, foundReportId:found.id, ...result, status:'suggested', createdAt:new Date().toISOString() }; db.matches.push(match); notify(lost.userId,'match','Potential match found', `${result.score}% possible match: ${found.category || 'item'} found near ${found.location || 'campus'}.`, `/reports/${found.id}`); notify(found.userId,'match','Potential match found', `${result.score}% possible match with a lost report.`, `/reports/${lost.id}`) }
}
const reportSchema = z.object({ type:z.enum(['lost','found']), description:z.string().min(10).max(2000), category:z.string().optional(), brand:z.string().nullable().optional(), model:z.string().nullable().optional(), color:z.string().nullable().optional(), distinguishingFeatures:z.array(z.string()).optional(), keywords:z.array(z.string()).optional(), location:z.string().nullable().optional(), dateOccurred:z.string().optional(), approximateTime:z.string().optional(), privateDetails:z.string().max(1000).optional(), contactEmail:z.string().email().optional().or(z.literal('')), contactWhatsapp:z.string().min(7).max(30).optional().or(z.literal('')) })

export async function createApp() {
  const app = express(); const upload = multer({ storage: multer.memoryStorage(), limits: { files:5, fileSize:5*1024*1024 }, fileFilter: (_req,file,cb) => cb(null, ['image/jpeg','image/png','image/webp'].includes(file.mimetype)) })
  const normalizeOrigin=(url='')=>url.trim().replace(/\/+$/,'')
  const allowedOrigins=(process.env.CLIENT_URL||'').split(',').map(normalizeOrigin).filter(Boolean)
  app.use(helmet({ crossOriginResourcePolicy:false })); app.use(cors({ origin(origin, callback) { if (!origin || !allowedOrigins.length || allowedOrigins.includes(normalizeOrigin(origin))) return callback(null,true); return callback(new Error('This origin is not allowed by FUTA FindIt.')) } })); app.use(express.json({ limit:'1mb' })); app.use('/api', rateLimit({ windowMs:15*60*1000, limit:250, standardHeaders:true, legacyHeaders:false }))
  app.get('/api/health', (_req,res) => ok(res,{ status:'ok', database:process.env.MONGODB_URI ? 'MongoDB configured' : 'demo memory mode' }))
  const safeUser=(user)=>{const value=user.toObject?user.toObject():user;const {passwordHash,...safe}=value;return {...safe,id:String(value._id||value.id)}}
  const safeReport=(report, viewerId='')=>publicReport(report, viewerId)
  const mongoAuth=(required=true)=>async(req,res,next)=>{const token=req.headers.authorization?.replace('Bearer ','');if(!token)return required?fail(res,401,'Please log in to continue.'):next();try{req.user=jwt.verify(token,secret);next()}catch{return fail(res,401,'Your session has expired. Please log in again.')}}
  app.post('/api/auth/register',async(req,res)=>{const parsed=z.object({username:z.string().min(3).regex(/^[a-zA-Z0-9._-]+$/),name:z.string().min(2),email:z.string().email(),contactEmail:z.string().email().optional().or(z.literal('')),contactWhatsapp:z.string().min(7).max(30).optional().or(z.literal('')),password:z.string().min(8),studentId:z.string().min(2),department:z.string().min(2),faculty:z.string().min(2),level:z.string().min(1)}).safeParse(req.body);if(!parsed.success)return fail(res,400,'Please complete all registration fields correctly.');const email=parsed.data.email.toLowerCase();const username=parsed.data.username.toLowerCase();if(await User.exists({email}))return fail(res,409,'An account with that email already exists.');if(await User.exists({username}))return fail(res,409,'That username is already taken.');const user=await User.create({...parsed.data,username,email,contactEmail:parsed.data.contactEmail||'',contactWhatsapp:parsed.data.contactWhatsapp||'',passwordHash:await bcrypt.hash(parsed.data.password,10)});ok(res,{token:tokenFor(user),user:safeUser(user)},201)})
  app.post('/api/auth/login',async(req,res)=>{const {email,password}=req.body||{};const user=await User.findOne({email:String(email||'').toLowerCase()});if(!user||!(await bcrypt.compare(password||'',user.passwordHash)))return fail(res,401,'Incorrect email or password.');if(user.suspended)return fail(res,403,'This account has been suspended.');ok(res,{token:tokenFor(user),user:safeUser(user)})})
  app.get('/api/auth/me',mongoAuth(),async(req,res)=>{const user=await User.findById(req.user.id);if(!user)return fail(res,401,'Account not found.');ok(res,safeUser(user))})
  const notifyMongo = async (userId, type, title, message, link = '') => {
    if (!userId) return
    await Notification.create({ userId, type, title, message, link, read: false })
  }
  const createMongoMatches = async (report) => {
    const candidates = await Report.find({ _id: { $ne: report._id }, type: report.type === 'lost' ? 'found' : 'lost', status: 'active' })
    for (const candidate of candidates) {
      const lost = report.type === 'lost' ? report : candidate
      const found = report.type === 'found' ? report : candidate
      const result = scoreMatch(lost, found)
      if (result.score < 40) continue
      await notifyMongo(lost.userId, 'match', 'Potential match found', `${result.score}% possible match: ${found.category || 'item'} at ${found.location || 'campus'}.`, `/reports/${found._id}`)
      await notifyMongo(found.userId, 'match', 'Potential match found', `${result.score}% possible match with a lost report.`, `/reports/${lost._id}`)
    }
  }
  app.post('/api/reports',mongoAuth(),async(req,res)=>{const parsed=reportSchema.safeParse(req.body);if(!parsed.success)return fail(res,400,'Check the report details and try again.');const analysis=await analyzeItemDescription(parsed.data.description);const user=await User.findById(req.user.id);const report=await Report.create({userId:req.user.id,username:user?.username||'',contactEmail:parsed.data.contactEmail||user?.contactEmail||'',contactWhatsapp:parsed.data.contactWhatsapp||user?.contactWhatsapp||'',...analysis,...parsed.data,category:parsed.data.category||analysis.category,keywords:parsed.data.keywords?.length?parsed.data.keywords:analysis.keywords,distinguishingFeatures:parsed.data.distinguishingFeatures?.length?parsed.data.distinguishingFeatures:analysis.distinguishingFeatures,images:[],status:'active'});await createMongoMatches(report);ok(res,safeReport(report),201)})
  app.get('/api/reports',mongoAuth(),async(req,res)=>{const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(50,Number(req.query.limit)||20),filter={};for(const key of ['type','category','location','status'])if(req.query[key])filter[key]=req.query[key];if(req.query.q){const parsed=await parseSearchQuery(req.query.q);filter.$or=parsed.keywords.map(word=>({$or:[{description:{$regex:word,$options:'i'}},{category:{$regex:word,$options:'i'}},{brand:{$regex:word,$options:'i'}},{color:{$regex:word,$options:'i'}},{location:{$regex:word,$options:'i'}},{keywords:{$regex:word,$options:'i'}}]}))}const [reports,total]=await Promise.all([Report.find(filter).sort({createdAt:-1}).skip((page-1)*limit).limit(limit),Report.countDocuments(filter)]);const users=await User.find({_id:{$in:reports.map((item)=>item.userId).filter(Boolean)}});const userMap=new Map(users.map((item)=>[String(item._id),item]));ok(res,{reports:reports.map((item)=>{const owner=userMap.get(String(item.userId));return safeReport({...item.toObject(),username:item.username||owner?.username||'',contactEmail:item.contactEmail||owner?.contactEmail||'',contactWhatsapp:item.contactWhatsapp||owner?.contactWhatsapp||''},req.user.id)}),pagination:{page,limit,total,pages:Math.ceil(total/limit)}})})
  app.get('/api/reports/:id',mongoAuth(false),async(req,res)=>{const report=await Report.findById(req.params.id);if(!report)return fail(res,404,'Report not found.');const owner=report.userId?await User.findById(report.userId):null;ok(res,safeReport({...report.toObject(),username:report.username||owner?.username||'',contactEmail:report.contactEmail||owner?.contactEmail||'',contactWhatsapp:report.contactWhatsapp||owner?.contactWhatsapp||''},req.user?.id))})
  app.get('/api/reports/:id/matches',mongoAuth(),async(req,res)=>{const report=await Report.findById(req.params.id);if(!report)return fail(res,404,'Report not found.');if(String(report.userId)!==req.user.id&&req.user.role!=='admin')return fail(res,403,'Only the report owner can see matches.');const type=report.type==='lost'?'found':'lost';const candidates=await Report.find({type,status:'active'});const matches=candidates.map((candidate)=>{const lost=report.type==='lost'?report:candidate;const found=report.type==='found'?report:candidate;const result=scoreMatch(lost,found);return{score:result.score,reasons:result.reasons,report:safeReport(candidate,req.user.id)}}).filter((item)=>item.score>=40).sort((a,b)=>b.score-a.score);ok(res,matches)})
  app.post('/api/reports/:id/images',mongoAuth(),upload.array('images',5),async(req,res)=>{const report=await Report.findById(req.params.id);if(!report)return fail(res,404,'Report not found.');if(String(report.userId)!==req.user.id)return fail(res,403,'You can only add images to your own report.');const images=req.files?.length?await uploadItemImages(req.files):await uploadDataUrls(Array.isArray(req.body.images)?req.body.images:[]);if(!images.length)return fail(res,400,'Choose at least one image.');report.images=images;await report.save();ok(res,safeReport(report))})
  app.post('/api/auth/register', async (req,res) => { const parsed = z.object({ username:z.string().min(3).regex(/^[a-zA-Z0-9._-]+$/), name:z.string().min(2), email:z.string().email(), contactEmail:z.string().email().optional().or(z.literal('')), contactWhatsapp:z.string().min(7).max(30).optional().or(z.literal('')), password:z.string().min(8), studentId:z.string().min(2), department:z.string().min(2), faculty:z.string().min(2), level:z.string().min(1) }).safeParse(req.body); if (!parsed.success) return fail(res,400,'Please complete all registration fields correctly.'); if (db.users.some((u) => u.email === parsed.data.email.toLowerCase())) return fail(res,409,'An account with that email already exists.'); if (db.users.some((u) => u.username === parsed.data.username.toLowerCase())) return fail(res,409,'That username is already taken.'); const user={ id:id(), ...parsed.data, username:parsed.data.username.toLowerCase(), email:parsed.data.email.toLowerCase(), contactEmail:parsed.data.contactEmail||'', contactWhatsapp:parsed.data.contactWhatsapp||'', passwordHash:await bcrypt.hash(parsed.data.password,10), role:'student', suspended:false, createdAt:new Date().toISOString() }; delete user.password; db.users.push(user); ok(res,{ token:tokenFor(user), user:userSafe(user) },201) })
  app.post('/api/auth/login', async (req,res) => { const parsed=z.object({ email:z.string().email(), password:z.string().min(1) }).safeParse(req.body); if(!parsed.success) return fail(res,400,'Enter a valid email and password.'); const user=db.users.find((u)=>u.email===parsed.data.email.toLowerCase()); if(!user || !(await bcrypt.compare(parsed.data.password,user.passwordHash))) return fail(res,401,'Incorrect email or password.'); if(user.suspended) return fail(res,403,'This account has been suspended.'); ok(res,{ token:tokenFor(user), user:userSafe(user) }) })
  app.get('/api/auth/me',auth(),(req,res)=> { const user=db.users.find((u)=>u.id===req.user.id); if(!user) return fail(res,401,'Account not found.'); ok(res,userSafe(user)) })
  app.post('/api/auth/logout',auth(),(_req,res)=>ok(res,{ message:'Logged out successfully.' }))
  app.get('/api/meta',(_req,res)=>ok(res,{ categories, locations }))
  app.post('/api/ai/analyze-description',auth(),async(req,res)=> { if(!req.body.description || req.body.description.length<3) return fail(res,400,'Please enter a longer description.'); ok(res,await analyzeItemDescription(req.body.description)) })
  app.post('/api/ai/parse-search',async(req,res)=>ok(res,await parseSearchQuery(req.body.query || '')))
  app.post('/api/ai/analyze-image',auth(),upload.array('images',5),(_req,res)=>ok(res,{ message:'Image analysis is not configured yet. Your images were validated successfully.' }))
  app.post('/api/reports',auth(),async(req,res)=> { const parsed=reportSchema.safeParse(req.body); if(!parsed.success) return fail(res,400,'Check the report details and try again.'); const analysis=await analyzeItemDescription(parsed.data.description); const user=db.users.find((u)=>u.id===req.user.id); const report={ id:id(), userId:req.user.id, username:user?.username||'', contactEmail:parsed.data.contactEmail||user?.contactEmail||'', contactWhatsapp:parsed.data.contactWhatsapp||user?.contactWhatsapp||'', ...analysis, ...parsed.data, category:parsed.data.category || analysis.category, keywords:parsed.data.keywords?.length ? parsed.data.keywords : analysis.keywords, distinguishingFeatures:parsed.data.distinguishingFeatures?.length ? parsed.data.distinguishingFeatures : analysis.distinguishingFeatures, images:[], status:'active', createdAt:new Date().toISOString(), updatedAt:new Date().toISOString() }; db.reports.unshift(report); createMatches(report); ok(res,publicReport(report),201) })
  app.get('/api/reports',async(req,res)=> { const page=Math.max(1,Number(req.query.page)||1), limit=Math.min(50,Number(req.query.limit)||20); let results=db.reports.filter((r)=>!req.query.type||r.type===req.query.type).filter((r)=>!req.query.category||r.category===req.query.category).filter((r)=>!req.query.location||r.location===req.query.location).filter((r)=>!req.query.status||r.status===req.query.status); const query=req.query.q; if(query){const parsed=await parseSearchQuery(query); const words=parsed.keywords; results=results.filter((r)=>words.some((word)=>`${r.description} ${r.category} ${r.brand||''} ${r.color||''} ${r.location||''} ${(r.keywords||[]).join(' ')}`.toLowerCase().includes(word)))} const total=results.length; ok(res,{ reports:results.slice((page-1)*limit,page*limit).map((item)=>publicReport(item)), pagination:{page,limit,total,pages:Math.ceil(total/limit)} }) })
  app.get('/api/reports/search',(req,res)=> { req.url='/api/reports'; app.handle(req,res) })
  app.get('/api/reports/:id',auth(false),(req,res)=> { const report=db.reports.find((r)=>r.id===req.params.id); if(!report) return fail(res,404,'Report not found.'); ok(res,publicReport(report,req.user?.id)) })
  app.patch('/api/reports/:id',auth(),ownReport,(req,res)=> { const parsed=reportSchema.partial().safeParse(req.body); if(!parsed.success) return fail(res,400,'Invalid report update.'); Object.assign(req.report,parsed.data,{updatedAt:new Date().toISOString()}); ok(res,publicReport(req.report)) })
  app.delete('/api/reports/:id',auth(),ownReport,(req,res)=> { db.reports=db.reports.filter((r)=>r.id!==req.report.id); ok(res,{ message:'Report deleted.' }) })
  app.get('/api/reports/:id/matches',auth(),(req,res)=> { const report=db.reports.find((r)=>r.id===req.params.id); if(!report)return fail(res,404,'Report not found.'); if(report.userId!==req.user.id && req.user.role!=='admin') return fail(res,403,'Only the report owner can see matches.'); const matches=db.matches.filter((m)=>m.lostReportId===report.id||m.foundReportId===report.id).map((m)=>({ ...m, report:publicReport(db.reports.find((r)=>r.id===(m.lostReportId===report.id?m.foundReportId:m.lostReportId)),req.user.id) })).filter((item)=>item.score>=40); ok(res,matches) })
  app.post('/api/reports/:id/reunite',auth(),ownReport,(req,res)=> { req.report.status='reunited'; req.report.updatedAt=new Date().toISOString(); ok(res,publicReport(req.report)) })
  app.post('/api/reports/:id/flag',auth(),(req,res)=> { const report=db.reports.find((r)=>r.id===req.params.id); if(!report) return fail(res,404,'Report not found.'); const reason=z.string().min(3).max(300).safeParse(req.body.reason); if(!reason.success) return fail(res,400,'Choose a reason for the flag.'); db.flags.push({id:id(),reportId:report.id,userId:req.user.id,reason:reason.data,status:'open',createdAt:new Date().toISOString()}); ok(res,{ message:'Thank you. The report has been sent for review.' },201) })
  app.post('/api/claims',auth(),(req,res)=> { const parsed=z.object({ lostReportId:z.string(), foundReportId:z.string(), ownershipExplanation:z.string().min(10).max(1500) }).safeParse(req.body); if(!parsed.success)return fail(res,400,'Please explain why this item belongs to you.'); const lost=db.reports.find((r)=>r.id===parsed.data.lostReportId), found=db.reports.find((r)=>r.id===parsed.data.foundReportId); if(!lost||!found||lost.type!=='lost'||found.type!=='found')return fail(res,400,'Choose a valid lost and found report.'); if(lost.userId!==req.user.id)return fail(res,403,'You can only claim using your own lost report.'); if(db.claims.some((c)=>c.lostReportId===lost.id&&c.foundReportId===found.id&&c.status==='pending'))return fail(res,409,'You already have a pending claim for this item.'); const owner=db.users.find((u)=>u.id===lost.userId); const claim={id:id(),...parsed.data,claimantId:req.user.id,finderId:found.userId,ownerUsername:owner?.username||'',ownerContactEmail:owner?.contactEmail||'',ownerContactWhatsapp:owner?.contactWhatsapp||'',status:'pending',handoverMethod:null,handoverLocation:null,handoverCode:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; db.claims.unshift(claim); lost.status='claim_pending'; found.status='claim_pending'; notify(found.userId,'claim','New claim request','Someone thinks a found item belongs to them.','/dashboard'); ok(res,claim,201) })
  app.get('/api/claims',auth(),(req,res)=>ok(res,db.claims.filter((c)=>c.claimantId===req.user.id||c.finderId===req.user.id||req.user.role==='admin')))
  app.get('/api/claims/:id',auth(),(req,res)=> {const claim=db.claims.find((c)=>c.id===req.params.id); if(!claim)return fail(res,404,'Claim not found.'); if(![claim.claimantId,claim.finderId].includes(req.user.id)&&req.user.role!=='admin')return fail(res,403,'You cannot view this claim.'); ok(res,claim)})
  app.post('/api/claims/:id/approve',auth(),(req,res)=> {const claim=db.claims.find((c)=>c.id===req.params.id); if(!claim)return fail(res,404,'Claim not found.'); if(claim.finderId!==req.user.id)return fail(res,403,'Only the finder can approve this claim.'); claim.status='ready_for_handover'; claim.handoverMethod=req.body.handoverMethod||'Campus Security'; claim.handoverLocation=req.body.handoverLocation||'Campus Security'; claim.handoverCode=`LF-${Math.floor(10000+Math.random()*90000)}`; claim.updatedAt=new Date().toISOString(); const lost=db.reports.find((r)=>r.id===claim.lostReportId), found=db.reports.find((r)=>r.id===claim.foundReportId); lost.status=found.status='claimed'; notify(claim.claimantId,'claim','Claim approved',`Your collection code is ${claim.handoverCode}. Keep it private.`,'/dashboard'); ok(res,claim) })
  app.post('/api/claims/:id/reject',auth(),(req,res)=> {const claim=db.claims.find((c)=>c.id===req.params.id);if(!claim)return fail(res,404,'Claim not found.');if(claim.finderId!==req.user.id)return fail(res,403,'Only the finder can reject this claim.');claim.status='rejected';notify(claim.claimantId,'claim','Claim rejected','The finder did not approve this claim.','/dashboard');ok(res,claim)})
  app.post('/api/claims/:id/complete',auth(),(req,res)=> {const claim=db.claims.find((c)=>c.id===req.params.id);if(!claim)return fail(res,404,'Claim not found.');if(claim.claimantId!==req.user.id&&claim.finderId!==req.user.id)return fail(res,403,'Only claim participants can complete handover.');claim.status='reunited';const lost=db.reports.find((r)=>r.id===claim.lostReportId),found=db.reports.find((r)=>r.id===claim.foundReportId);lost.status=found.status='reunited';notify(claim.finderId,'reunited','Item reunited','This item has been collected by the owner.','/dashboard');notify(claim.claimantId,'reunited','Item reunited','You confirmed that the item has been collected from the finder.','/dashboard');ok(res,{...claim,finalState:'collected_by_owner'})})
  app.get('/api/claims/:id/messages',auth(),(req,res)=> {const claim=db.claims.find((c)=>c.id===req.params.id);if(!claim)return fail(res,404,'Claim not found.');if(![claim.claimantId,claim.finderId].includes(req.user.id))return fail(res,403,'Only claim participants can read messages.');ok(res,db.messages.filter((m)=>m.claimId===claim.id))})
  app.post('/api/claims/:id/messages',auth(),(req,res)=> {const claim=db.claims.find((c)=>c.id===req.params.id);if(!claim)return fail(res,404,'Claim not found.');if(![claim.claimantId,claim.finderId].includes(req.user.id))return fail(res,403,'Only claim participants can send messages.');const parsed=z.string().min(1).max(1000).safeParse(req.body.message);if(!parsed.success)return fail(res,400,'Message must be between 1 and 1000 characters.');const message={id:id(),claimId:claim.id,senderId:req.user.id,message:parsed.data,createdAt:new Date().toISOString()};db.messages.push(message);notify(req.user.id===claim.finderId?claim.claimantId:claim.finderId,'message','New claim message','You have a new message about your claim.','/dashboard');ok(res,message,201)})
  app.get('/api/notifications',auth(),(req,res)=>ok(res,db.notifications.filter((n)=>n.userId===req.user.id)))
  app.patch('/api/notifications/:id/read',auth(),(req,res)=>{const note=db.notifications.find((n)=>n.id===req.params.id&&n.userId===req.user.id);if(!note)return fail(res,404,'Notification not found.');note.read=true;ok(res,note)})
  app.patch('/api/notifications/read-all',auth(),(req,res)=>{db.notifications.filter((n)=>n.userId===req.user.id).forEach((n)=>n.read=true);ok(res,{message:'All notifications marked as read.'})})
  app.get('/api/admin/stats',auth(),admin,(_req,res)=>ok(res,{ totalUsers:db.users.length,lostReports:db.reports.filter(r=>r.type==='lost').length,foundReports:db.reports.filter(r=>r.type==='found').length,activeReports:db.reports.filter(r=>r.status==='active').length,pendingClaims:db.claims.filter(c=>c.status==='pending').length,reunitedItems:db.reports.filter(r=>r.status==='reunited').length,flaggedReports:db.flags.filter(f=>f.status==='open').length }))
  app.get('/api/admin/reports',auth(),admin,(_req,res)=>ok(res,db.reports.map(publicReport))); app.get('/api/admin/users',auth(),admin,(_req,res)=>ok(res,db.users.map(userSafe))); app.get('/api/admin/claims',auth(),admin,(_req,res)=>ok(res,db.claims)); app.patch('/api/admin/users/:id/suspend',auth(),admin,(req,res)=>{const user=db.users.find(u=>u.id===req.params.id);if(!user)return fail(res,404,'User not found.');user.suspended=!user.suspended;ok(res,userSafe(user))})
  // Safe contact requests never disclose an email, phone number, or student ID. The finder
  // must prove they have a real found-item report before the lost-item owner is notified.
  app.get('/api/my-reports',auth(),(req,res)=>ok(res,db.reports.filter((report)=>report.userId===req.user.id).map(publicReport)))
  app.post('/api/reports/:id/contact',auth(),(req,res)=> { const lostReport=db.reports.find((report)=>report.id===req.params.id); const parsed=z.object({ foundReportId:z.string(), message:z.string().min(10).max(500), handoverLocation:z.string().min(2).max(120).optional() }).safeParse(req.body); if(!lostReport||lostReport.type!=='lost') return fail(res,404,'Lost report not found.'); if(!parsed.success) return fail(res,400,'Include a short, helpful message.'); const foundReport=db.reports.find((report)=>report.id===parsed.data.foundReportId); if(!foundReport||foundReport.type!=='found'||foundReport.userId!==req.user.id) return fail(res,403,'You can only contact an owner using one of your own found-item reports.'); if(lostReport.userId===req.user.id) return fail(res,400,'You cannot contact yourself about your own report.'); if(db.contactRequests.some((request)=>request.lostReportId===lostReport.id&&request.foundReportId===foundReport.id&&request.status==='pending')) return fail(res,409,'A contact request for these reports is already awaiting a response.'); const request={ id:id(), lostReportId:lostReport.id, foundReportId:foundReport.id, finderId:req.user.id, ownerId:lostReport.userId, message:parsed.data.message, handoverLocation:parsed.data.handoverLocation || foundReport.location || lostReport.location || 'FUTA Campus', status:'pending', createdAt:new Date().toISOString() }; db.contactRequests.unshift(request); notify(lostReport.userId,'safe_contact','A finder may have your item',`A verified finder linked a found-item report to yours. Suggested meetup: ${request.handoverLocation}. Review it and continue with private verification.`,`/reports/${foundReport.id}`); ok(res,{ message:`Safe contact request sent. Suggested meetup: ${request.handoverLocation}.`, request },201) })
  app.get('/api/contact-requests',auth(),(req,res)=>ok(res,db.contactRequests.filter((request)=>request.ownerId===req.user.id||request.finderId===req.user.id)))
  app.patch('/api/contact-requests/:id',auth(),(req,res)=> { const request=db.contactRequests.find((item)=>item.id===req.params.id); if(!request) return fail(res,404,'Contact request not found.'); if(request.ownerId!==req.user.id) return fail(res,403,'Only the lost-item owner can respond to this request.'); if(!['accepted','rejected'].includes(req.body.status)) return fail(res,400,'Choose accepted or rejected.'); request.status=req.body.status; notify(request.finderId,'safe_contact',`Contact request ${request.status}`,request.status==='accepted'?'The owner will use the private claim flow to verify ownership.':'The owner did not accept this contact request.','/dashboard'); ok(res,request) })
  app.get('/api/reports/:id/qr',async(req,res)=> { const report=db.reports.find((item)=>item.id===req.params.id); if(!report) return fail(res,404,'Report not found.'); const url=`${process.env.CLIENT_URL || 'http://localhost:5173'}/reports/${report.id}`; const image=await QRCode.toDataURL(url,{ margin:1, width:360, color:{dark:'#102e45',light:'#ffffff'} }); ok(res,{ url, image }) })
  app.post('/api/reports/duplicates',auth(),async(req,res)=> { const parsed=z.object({ description:z.string().min(3), type:z.enum(['lost','found']) }).safeParse(req.body); if(!parsed.success) return fail(res,400,'Enter a report description first.'); const details=await parseSearchQuery(parsed.data.description); const matches=db.reports.filter((item)=>item.type===parsed.data.type&&item.status==='active').map((item)=>({ report:publicReport(item), shared:details.keywords.filter((word)=>(item.keywords||[]).includes(word)) })).filter((item)=>item.shared.length>=2).slice(0,3); ok(res,matches) })
  app.get('/api/analytics/insights',(_req,res)=> { const count=(key)=>Object.entries(db.reports.reduce((all,item)=>{const value=item[key]||'Other';all[value]=(all[value]||0)+1;return all},{})).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([label,value])=>({label,value})); const reunited=db.reports.filter((item)=>item.status==='reunited').length; ok(res,{ topCategories:count('category'), topLocations:count('location'), recoveryRate:db.reports.length?Math.round(reunited/db.reports.length*100):0, totalReports:db.reports.length, message:'These patterns help campus security focus on the places where students most often need help.' }) })
  // Browser fallback image storage for the demo. A production Cloudinary/S3 service
  // can replace this endpoint without changing the frontend upload experience.
  app.post('/api/reports/:id/images',auth(),(req,res)=> { const report=db.reports.find((item)=>item.id===req.params.id); if(!report) return fail(res,404,'Report not found.'); if(report.userId!==req.user.id) return fail(res,403,'You can only add images to your own report.'); const images=Array.isArray(req.body.images)?req.body.images:[]; const valid=images.length<=5&&images.every((image)=>typeof image==='string'&&/^data:image\/(jpeg|png|webp);base64,/.test(image)&&image.length<=180000); if(!valid) return fail(res,400,'Upload up to five JPEG, PNG, or WEBP images under 130KB each.'); report.images=images; report.updatedAt=new Date().toISOString(); ok(res,publicReport(report)) })
  app.use((err,_req,res,_next)=> { if(err instanceof multer.MulterError)return fail(res,400,'Image upload failed. You can upload up to five JPEG, PNG, or WEBP files, each under 5MB.'); console.error(err); fail(res,500,'Something went wrong. Please try again.') })
  return app
}
